name: lint and test
on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    rust:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ”§ Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: ğŸ”¬ Install nextest
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-nextest

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v3

            - name: ğŸ“ Rust cache
              uses: Swatinem/rust-cache@v2

            - name: ğŸ“– Check formatting
              run: cargo fmt --check

            - name: ğŸ“ Run clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

            - name: ğŸ§ª Run tests
              run: cargo nextest run --no-fail-fast

            - name: ğŸ“š Run doctests
              run: cargo test --doc
